
services:
  - type: web
    name: sikkimspirits
    runtime: node
    plan: free
    buildCommand: npm install && npx vite build && npx esbuild server/index.ts --platform=node --packages=external --bundle --format=esm --outdir=dist
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /api/health
    
databases:
  - name: sikkimspirits-db
    databaseName: sikkimspirits
    user: sikkimspirits_user
    plan: free
